### ISSUE TITLE
Panic whenever the controller tries to handle an ApplicationSet

### ISSUE THREAD

**Issue by mattparkes** [argoproj-labs/applicationset#49]
I've done a basic install as per the README with `kustomize` and then when I `kubectl apply` the example `applicationset.yaml` this is what I get:

```
2020-09-17T23:10:42.939Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8081"}
2020-09-17T23:10:42.941Z	INFO	setup	starting manager
2020-09-17T23:10:42.941Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-09-17T23:10:43.041Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "applicationset", "source": "kind source: /, Kind="}
2020-09-17T23:10:43.142Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "applicationset", "source": "kind source: /, Kind="}
2020-09-17T23:10:43.142Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "applicationset", "source": "kind source: /, Kind="}
time="2020-09-17T23:10:43Z" level=info msg="processing event for cluster secret" name=argocd-cluster-uat-corporate namespace=argocd type=createSecretEventHandler
2020-09-17T23:10:43.242Z	INFO	controller-runtime.controller	Starting Controller	{"controller": "applicationset"}
2020-09-17T23:10:43.242Z	INFO	controller-runtime.controller	Starting workers{"controller": "applicationset", "worker count": 1}
time="2020-09-17T23:10:43Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
time="2020-09-17T23:10:43Z" level=info msg="generated 0 applications" generator="&{}"
time="2020-09-17T23:10:43Z" level=info msg="processing event for cluster secret" name=cluster-kubernetes.default.svc-3396314289 namespace=argocd type=createSecretEventHandler
time="2020-09-17T23:10:43Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
time="2020-09-17T23:10:43Z" level=info msg="processing event for cluster secret" name=argocd-cluster-uat-faketest namespace=argocd type=createSecretEventHandler
time="2020-09-17T23:10:43Z" level=info msg="listed ApplicationSets" count=1 type=createSecretEventHandler
time="2020-09-17T23:10:43Z" level=info msg="matched cluster secret" cluster=cluster-kubernetes.default.svc-3396314289
time="2020-09-17T23:10:43Z" level=info msg="matched cluster secret" cluster=argocd-cluster-uat-faketest
time="2020-09-17T23:10:43Z" level=info msg="matched cluster secret" cluster=argocd-cluster-uat-corporate
E0917 23:10:43.243288       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 293 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x177b380, 0x28ed7d0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/runtime/runtime.go:48 +0x82
panic(0x177b380, 0x28ed7d0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).generateApplications(0xc0006b0690, 0x163e1ce, 0xe, 0xc000b43000, 0x14, 0xc00047c090, 0x9, 0x0, 0x0, 0xc00047c09a, ...)
	/workspace/pkg/controllers/applicationset_controller.go:97 +0x4f9
github.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).Reconcile(0xc0006b0690, 0xc00047c09a, 0x6, 0xc00047c090, 0x9, 0x0, 0xbfd1191cce79c96a, 0xc000820090, 0xc00074a1b8)
	/workspace/pkg/controllers/applicationset_controller.go:65 +0x2c3
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007b40c0, 0x17e4180, 0xc0008d3920, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007b40c0, 0xc000502500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0007b40c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00015a560)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00015a560, 0x3b9aca00, 0x0, 0x1, 0xc0006c7980)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00015a560, 0x3b9aca00, 0xc0006c7980)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15efe79]
goroutine 293 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/runtime/runtime.go:55 +0x105
panic(0x177b380, 0x28ed7d0)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).generateApplications(0xc0006b0690, 0x163e1ce, 0xe, 0xc000b43000, 0x14, 0xc00047c090, 0x9, 0x0, 0x0, 0xc00047c09a, ...)
	/workspace/pkg/controllers/applicationset_controller.go:97 +0x4f9
github.com/argoproj-labs/applicationset/pkg/controllers.(*ApplicationSetReconciler).Reconcile(0xc0006b0690, 0xc00047c09a, 0x6, 0xc00047c090, 0x9, 0x0, 0xbfd1191cce79c96a, 0xc000820090, 0xc00074a1b8)
	/workspace/pkg/controllers/applicationset_controller.go:65 +0x2c3
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007b40c0, 0x17e4180, 0xc0008d3920, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007b40c0, 0xc000502500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0007b40c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00015a560)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00015a560, 0x3b9aca00, 0x0, 0x1, 0xc0006c7980)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00015a560, 0x3b9aca00, 0xc0006c7980)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.6/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:193 +0x305
```

**Comment by alxbse** [comment]
Had the same issue myself, this was fixed in #47
